config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'item/page'
  get 'about/page'
  get '/search', to:"articles#search"
  get '/category/:id', to: "articles#category", as: "category"

  resources :users
  resources :articles
  resources :transactions, only: [:create]
  get 'checkout/success', to: 'transactions#success'

  root 'home#page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
    @featured_article = Article.all.sample
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/page.html.erb
<%# Heading for page and links to creating an aricle and browsing articles %>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
            <h1 class="display-4">Where Readers and Writers Connect</h1>
            <hr class="my-4">
            <%= link_to "Write for us", new_article_path, class: "btn btn-primary btn-lg mx-2 my-2" %>
            <%= link_to "Start reading", item_page_path, class: "btn btn-primary btn-lg mx-2 my-2" %>
        </div>

        <div class="col-md-6">
        </div>
    </div>
</div>

<%# Featured article - link to randomly selected article, with hyperlinks in the title and image to link to article show page  %>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
            <h2 class="display-4">Featured </h2>
            <hr class="my-4">
            <div class="card mb-3 mx-4" style="max-width: 540px;">
            <div class="row g-0 d-inline-flex p-2 flex-wrap align-items-start">
                <div class="col-md-4">
                <%= link_to image_tag(@featured_article.thumbnail, :alt => "Featured Article", height: "170px", width: "170px" ), article_path(@featured_article) if @featured_article.thumbnail.attached? %>
                </div>
                <div class="col-md-8">
                <div class="card-body">
                <h5> <%= link_to @featured_article.title, article_path(@featured_article), class: "card-title" %> </h5>
                <p class="card-text"> <%= @featured_article.description.truncate(160)%> </p>
                </div>
                </div>
            </div>
            </div>
        </div>

<%# Category buttons for filtering articles by category %>
        <div class="col-md-6">
            <h2 class="display-4">Categories</h2>
            <hr class="my-4">
            <% Category.all.each do |category| %>
            <a class="btn btn-info mx-2 my-2 btn-primary-spacing" href="<%= category_path(category.id) %>" role="button"><%= category.name %></a>
            <% end %>
        </div>
    </div>
</div>